esphome:
  name: m5-stack-rotary-button
  friendly_name: m5 Stack Rotary Button
  name_add_mac_suffix: false
  project:
    name: Trumpedroid.m5_dial
    version: "1.0"

  platformio_options:
    lib_deps:
      - WiFi
      - SPI
      - FS
      - Wire
      - EEPROM
      - ArduinoJson
      - m5stack/M5Unified@0.1.14
      - m5stack/M5Dial


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "29D3rvbXO/RMMRTvaaM4L89WAZIJ+Q3UmbTzNiTbWcQ="

ota:
  - platform: esphome
    password: "5c04e5cd5af7585230e7cc12683d1d7a"

wifi:
  ssid: THE_Internet_LA
  password: 30FamKrimm

captive_portal:
    
logger:
  level: DEBUG


external_components:
  - source:
      type: local
      path: C:\ESPHomeSpace\m5-dial-for-esphome\components

shys_m5_dial:
  name: Dial
  screen_off_time: 90000
  rotary_step_width: 5
  long_press_duration: 1200
  font: FreeSans12pt7b
  font_factor: 1

  devices:
    shotTimer_state:
      - entity: sensor.mr022480_shot_timer
        name: ShotTimer
        modes:
          shotTimer_state_mode:
            min_shot_time: 0
            max_shot_time: 30
    plantHappy_state:
    - entity: sensor.b_parasite_ecf3_bonsai_moisture
      name: Bonsai
      modes:
        plantHappy_mode:
          min_moisture: 0
          med_moisture: 50
          max_moisture: 80
    - entity: sensor.b_parasite_808f_sofa_garl_moisture
      name: Sofa Garl
      modes:
        plantHappy_mode:
          min_moisture: 0
          med_moisture: 70
          max_moisture: 80

